const friends = [
  {
    name: 'Hon. Temidayo Ayeni',
    img: 'img/ayeni.jpg',
    friend: 'Best Man',
    social: ['#x', '#facebook', '#Linkedin', '#instergram'],
    type: 'groom',
  },
  {
    name: 'Amòfin Tope Aboloyinjo',
    img: 'img/topeAboloyinjo.jpg',
    friend: 'Best friend',
    social: [
      'https://x.com/topeaboloyinjo',
      'https://www.facebook.com/topeaboloyinjo',
      '#Linkedin',
      'https://www.instagram.com/topeaboloyinjo/',
    ],
    type: 'groom',
  },
  {
    name: 'Patriot Tolulope Folorunso',
    img: 'img/tolu.jpg',
    friend: 'Best friend',
    social: [
      'https://x.com/Developer_Tolu',
      'https://www.facebook.com/Tolu4you/',
      'https://www.linkedin.com/in/tolufolorunso/',
      'https://www.instagram.com/developer_tolu/',
    ],
    type: 'groom',
  },
  {
    name: 'Engr. Samuel Adeyemi',
    img: 'img/samuel_bestman.jpg',
    friend: 'Best Friend',
    social: ['#x', '#facebook', '#Linkedin', '#instergram'],
    type: 'groom',
  },
  {
    name: 'Mr. Adebanji Mathew',
    img: 'img/adebanji.jpg',
    friend: 'Best friend',
    social: ['#x', '#facebook', '#Linkedin', '#instergram'],
    type: 'groom',
  },
  {
    name: 'Mr. Adeola Adewale',
    img: 'img/adewale.jpg',
    friend: 'Best friend',
    social: ['#x', '#facebook', '#Linkedin', '#instergram'],
    type: 'groom',
  },
  {
    name: 'Mr. Bankole Ademola',
    img: 'img/ademola.jpg',
    friend: 'Best friend',
    social: ['#x', '#facebook', '#Linkedin', '#instergram'],
    type: 'groom',
  },
  {
    name: 'Mr. Oluwaseun Olaniyi Agboola',
    img: 'https://placehold.co/600x400',
    friend: 'Best friend',
    social: ['#x', '#facebook', '#Linkedin', '#instergram'],
    type: 'groom',
  },
  {
    name: 'Mr. Ibrahim Akeem',
    img: 'https://placehold.co/600x400',
    friend: 'Best friend',
    social: ['#x', '#facebook', '#Linkedin', '#instergram'],
    type: 'groom',
  },
  {
    name: 'Mr. Alaba Adekunle',
    img: 'https://placehold.co/600x400',
    friend: 'Best friend',
    social: ['#x', '#facebook', '#Linkedin', '#instergram'],
    type: 'groom',
  },

  {
    name: 'Ore Iyawo name',
    img: 'https://placehold.co/600x400',
    friend: 'Best friend',
    social: ['#x', '#facebook', '#Linkedin', '#instergram'],
    type: 'bride',
  },
  {
    name: 'Ore Iyawo name',
    img: 'https://placehold.co/600x400',
    friend: 'Best friend',
    social: ['#x', '#facebook', '#Linkedin', '#instergram'],
    type: 'bride',
  },
  {
    name: 'Ore Iyawo name',
    img: 'https://placehold.co/600x400',
    friend: 'Best friend',
    social: ['#x', '#facebook', '#Linkedin', '#instergram'],
    type: 'bride',
  },
];

export default friends;
